version: '3.8'
services:
  front:
    build:
      context: web
      dockerfile: Dockerfile.web
    ports:
      - 8080:80
    volumes:
      - '${PWD}/web:/var/www/html:ro'
    networks:
      - bg-cities-net
    depends_on:
      - db
    restart: on-failure

  db:
    build:
      context: db
      dockerfile: Dockerfile.db
    networks:
      - bg-cities-net
    environment:
      MYSQL_ROOT_PASSWORD: 12345
networks:
  bg-cities-net:
